name: burgger_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  bloc: ^9.2.1
  build_runner: ^2.4.6
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_credit_card: ^4.1.0
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.3.1
  flutter_svg: ^2.2.4
  freezed: ^3.2.5
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  get_it: ^9.2.0
  google_fonts: ^8.0.2
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  json_annotation: 4.11.0
  
  json_serializable: ^6.13.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.9.2
  retrofit_generator: ^10.2.3
  shared_preferences: ^2.5.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/